# Generated by Django 4.1.4 on 2023-01-31 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("source_language", models.TextField()),
                ("target_language", models.TextField()),
                (
                    "job_field",
                    models.CharField(
                        choices=[
                            ("A", "Art"),
                            ("B", "Business"),
                            ("C", "Computers"),
                            ("ED", "Education"),
                            ("ENG", "Engineering"),
                            ("F", "Finance"),
                            ("L", "Law"),
                            ("LIT", "Literature"),
                            ("M", "Medicine"),
                            ("SC", "Science"),
                            ("SS", "Social Sciences"),
                            ("TECH", "Technology"),
                        ],
                        default="LIT",
                        max_length=4,
                    ),
                ),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
                ("text", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
