# Generated by Django 4.1.4 on 2023-01-31 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_jobfield_job"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"managed": False},
        ),
    ]
