# Generated by Django 4.1.4 on 2023-02-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_job_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={},
        ),
    ]
