# Generated by Django 4.1.4 on 2023-02-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_userprofile_token_balance"),
        ("app", "0003_alter_job_options"),
    ]

    operations = []
