# Generated by Django 4.1.4 on 2023-02-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_job_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="budget",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.TextField(unique=True),
        ),
    ]
