# Generated by Django 4.1.4 on 2023-02-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_job_options"),
        ("app", "0006_alter_job_budget"),
    ]

    operations = []
