# Generated by Django 4.1.4 on 2023-02-02 10:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0006_alter_job_budget"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="to_user",
        ),
        migrations.AddField(
            model_name="message",
            name="job",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app.job"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="send_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
