# Generated by Django 4.1.4 on 2023-02-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_job_is_assigned_job_is_completed_alter_job_title_and_more"),
        ("app", "0008_message_to_user_alter_message_from_user"),
    ]

    operations = []
