# Generated by Django 4.1.4 on 2023-02-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_job_options"),
        ("app", "0008_message_to_user_alter_message_from_user"),
    ]

    operations = []
