# Generated by Django 4.1.4 on 2023-02-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_merge_20230202_1603"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_assigned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.TextField(unique=True),
        ),
    ]
