# Generated by Django 4.1.4 on 2023-02-02 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_job_budget_alter_job_title"),
        ("app", "0009_merge_20230202_1309"),
    ]

    operations = []
