# Generated by Django 4.1.4 on 2023-02-02 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_job_budget_alter_job_title"),
        ("app", "0010_jobbid"),
    ]

    operations = []
