# Generated by Django 4.1.4 on 2023-02-02 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_merge_20230202_1917"),
        ("app", "0011_merge_20230202_1926"),
    ]

    operations = []
