# Generated by Django 4.1.4 on 2023-02-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_merge_20230202_2220"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_translator",
            field=models.BooleanField(default=False),
        ),
    ]
