# Generated by Django 4.1.4 on 2023-02-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_merge_20230203_1012"),
        ("app", "0012_merge_20230202_2220"),
    ]

    operations = []
