# Generated by Django 4.1.4 on 2023-02-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_job_is_assigned_job_is_completed_alter_job_title"),
        ("app", "0013_merge_20230203_1015"),
    ]

    operations = []
