# Generated by Django 4.1.4 on 2023-02-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_job_translator_alter_job_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="translation",
            field=models.TextField(blank=True),
        ),
    ]
