# Generated by Django 4.1.4 on 2023-02-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_job_is_assigned_job_is_completed_alter_job_title"),
        ("app", "0014_job_translator_alter_job_user"),
    ]

    operations = []
