# Generated by Django 4.1.4 on 2023-02-03 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_merge_20230203_1049"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_to",
                to="app.jobbid",
            ),
            preserve_default=False,
        ),
    ]
