# Generated by Django 4.1.4 on 2023-02-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_job_translation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="translation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
