# Generated by Django 4.1.4 on 2023-02-03 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_job_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_to",
                to="app.jobbid",
            ),
        ),
    ]
