# Generated by Django 4.1.4 on 2023-02-04 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_alter_userprofile_is_translator"),
        ("app", "0016_job_dispute"),
    ]

    operations = []
