# Generated by Django 4.1.4 on 2023-02-05 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_alter_userprofile_is_translator"),
        ("app", "0015_alter_job_job_field"),
        ("app", "0016_alter_job_assigned_to"),
        ("app", "0016_alter_job_translation"),
        ("app", "0016_job_dispute"),
        ("app", "0016_rating"),
    ]

    operations = []
