# Generated by Django 4.1.4 on 2023-02-04 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_alter_job_translation"),
        ("app", "0017_merge_20230204_1555"),
    ]

    operations = []
