# Generated by Django 4.1.4 on 2023-02-04 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_alter_job_job_field"),
        ("app", "0017_merge_20230204_1555"),
    ]

    operations = []
