# Generated by Django 4.1.4 on 2023-02-04 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_rating"),
        ("app", "0018_merge_20230204_1842"),
    ]

    operations = []
