# Generated by Django 4.1.4 on 2023-02-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_merge_20230204_2147"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="translation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_translator",
            field=models.BooleanField(default=False),
        ),
    ]
