# Generated by Django 4.1.4 on 2023-02-05 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_alter_job_job_field"),
        ("app", "0016_rating"),
        ("app", "0018_merge_20230204_1622"),
        ("app", "0018_merge_20230204_1842"),
    ]

    operations = []
