# Generated by Django 4.1.4 on 2023-02-04 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_merge_20230204_1622"),
        ("app", "0019_merge_0016_rating_0018_merge_20230204_1842"),
    ]

    operations = []
