# Generated by Django 4.1.4 on 2023-02-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0020_merge_20230204_1938"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="is_translator",
            field=models.BooleanField(default=False),
        ),
    ]
